### ISSUE TITLE
EZID reports identifier already exists when recreating a deleted ARK ID

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#387]
Mark Reyes reported on 2/8:

I'd like to put something on your EZID radar.  Not a big issue, but one that comes up when we perform Merritt Benchmark testing.
If we create an ARK in EZID and then we delete it, there still seems to be something remaining that prevents us from recreating it.
Maybe this is a misunderstanding of how the delete within EZID works.  Maybe deleting it just prevents it from being viewed.
Here is an example:
$ curl https://ezid.cdlib.org/id/ark:/99999/fk43r2fg53
        error: bad request - no such identifier

$ curl -X PUT https://merritt:XXXXX@ezid.cdlib.org/id/ark:/99999/fk43r2fg53
        error: bad request - identifier already exists

If this is normal behavior for EZID, then please let us know.

**Comment by rushirajnenuji** [comment]
Upon further investigation, this issue is stemming from similar problem that are discussed in #394 and #395 

Whenever a `DELETE` identifier operation is executed on the identifier, current logic does not remove the identifier record from the async queues. Because of this, the service returns `error: bad request - identifier already exists`. 

**Steps to recreate:**
1. Create a test identifier (I tested this theory with this identifier: [ark:/99999/fk8test0313](https://ezid-stg.cdlib.org/id/ark:/99999/fk8test0313).
2. Verify that the identifier is created successfully in EZID system.
3. Delete this identifier using HTTP DELETE operation via the EZID API. 
4. Try to _re-create_ the same identifier as in Step 1. This will result in `error: bad request - identifier already exists`
5. Delete the identifier record from the `ezidapp_searchindexerqueue` and `ezidapp_refidentifier` queues. 
6. Try to _re-create_ the same identifier as in Step 1. This time the operation will go through and the identifier will be successfully _recreated_

**Resolution**
It looks like we do not need to take any additional steps for this, resolution for #394 should fix this issue as well.

**Comment by jsjiang** [comment]
@rushirajnenuji Your analysis looks good. It is the identifier record left in the 'ezidapp_searchindexerqueue' and 'ezidapp_refidentifier' tables that are preventing re-creating a previously deleted identifier. 

For the resolution, how about:
1. Delete the identifier from the `ezidapp_searchindexerqueue` and `ezidapp_refidentifier` tables while deleting it from the `ezidapp_identifier' table to make these 3 tables in sync real time. 

The `ezidapp_searchindexerqueue` table has a foreign key constrain with the ID field in `ezidapp_refidentifier` table, the related entries should be deleted at the same time.

2. Use a background job to remove completed transactions from the Binder, Crossref, Datacite queues. In this case deleting the entries by transaction status but not by refidentifier_id as the same identifier may have multiple entries in the same queue. 

Jing

**Comment by jsjiang** [comment]
To help Merritt restore their testing workflow, how about we write a one time script to
1. Identify all previously deleted IDs (not in the ezidapp_identifier table) but are still kept in the ezidapp_searchindexerqueue and ezidapp_refidentifier tables
2. Delete these identifiers from the ezidapp_searchindexerqueue and ezidapp_refidentifier tables

Jing
