### ISSUE TITLE
Configure Matomo Tracking Code for EZID

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#435]
https://developer.matomo.org/guides/tracking-javascript-guide

**Comment by mariagould** [comment]
Hi @marisastrong can you provide more details about the Matomo transition so we can plan the work accordingly? Thanks.

**Comment by datadavev** [comment]
Does Mataomo support programmatic creation of events? e.g. Plausible[^1] allows POST to an API endpoint to record an event which is very helpful for tracking API access where a browser JS client is not available.

This would be useful in EZID since a lot of traffic goes through the API rather than the UI. 

[^1]: https://plausible.io/docs/events-api

**Comment by marisastrong** [comment]
@datadavev I missed the query earlier on tracking events.  I was able to find this documentation in Matomo that seems to serve this purpose.

https://developer.matomo.org/api-reference/tracking-api
