### ISSUE TITLE
[TEST] Verify Data Consistency Between Database and OpenSearch for Historic and Current Date Ranges

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#686]
**Describe the functionality to be tested**
We need to verify that the results returned from the database and OpenSearch are consistent in terms of total number of records, identifiers, and metadata for two separate date ranges: one historic and one current.

**Describe the test scenario**
1. Define two separate date ranges for testing:
   a. Historic range: Randomly select a date range from the earliest available data up to just before the current range begins.
   b. Current range: Use the most recent data, e.g., the last 7 days.

2. For each date range:
   a. Execute a query on the database to retrieve records within the range.
   b. Execute an equivalent query on OpenSearch to retrieve the same set of records.
   c. Compare the results from both queries:
      - Total number of records returned
      - Identifiers of the records
      - Metadata associated with each record

**Expected outcome**
For both the historic and current date ranges:
1. The total number of records returned from the database and OpenSearch should be identical.
2. The identifiers of the records should match exactly between the two result sets.
3. The metadata associated with each record should be consistent between the database and OpenSearch results.
4. This consistency should be maintained across both the randomly selected historic range and the current range.

**Who would benefit from this test?**
Devs - verifying data consistency between the database and OpenSearch index.

**Comment by sfisher** [comment]
It seems like we didn't test exactly this, but tested year ranges.  I can test this manually for most accuracy and the date ranges are only exposed in the "manage" page.

-----

Example SQL query for range, using ISO-8601 dates, you may copy these same dates in the OpenSearch dashboard and it correctly converts them to local time.

```
SELECT count(*) as created_identifiers
  FROM ezidapp_searchidentifier
  WHERE createTime BETWEEN
  	UNIX_TIMESTAMP(STR_TO_DATE('2024-07-01T00:00:00Z', '%Y-%m-%dT%H:%i:%sZ')) AND
  	UNIX_TIMESTAMP(STR_TO_DATE('2024-07-08T00:00:00Z', '%Y-%m-%dT%H:%i:%sZ'))
```



![Image](https://github.com/user-attachments/assets/dd991285-d56f-4936-9285-d067c637b1b9)



I'm testing on stage since the updates are not live in production yet:

Range 2024-07-01 to 2024-07-08 -- number of results match at (only 2 results)

---

Range 2019-07-01 to 2019-07-08 -- Database: 21,909, OpenSearch 21,909



![Image](https://github.com/user-attachments/assets/26ea436f-e271-4e5e-ae90-b97cb3616c1e)


![Image](https://github.com/user-attachments/assets/4ef0cfa1-b9ec-4813-bf4e-5bd60762ec93)



-----

## The date range tests for year searches

### Test pubyear_from and pubyear_to parameters

```
pubyear_from={year}
pubyear_to={year}
pubyear_from={start_year}&pubyear_to={end_year}
```

pubyear=2020  (and Open Context publisher to limit to reasonable results size)  -- Gave 29 results on both systems.


We went through this result set `"resourcePublisher:(Open Context) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2021"` and checked the missing items in Stage and they didn't exist in the
database for stage, either so results are functionally equivalent.  Some sorting of foreign characters was different between the two systems.

**Comment by adambuttrick** [comment]
Tests pass as part of release - https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
