### ISSUE TITLE
Refactor "Download report in CSV format"

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#718]
After login an EZID user can download statistic report using "Download report in CSV format" functionality in the Dashboard page. There are few issues that need fixes:
1. Numbers in the UI do not match to the numbers in the downloaded CSV file
2. Accessing the "Download report in CSV" always triggers an Internal Server Error. Add error handling to avoid sending false error notifications.

```
Subject: [Django] ERROR (EXTERNAL IP): Internal Server Error: /dashboard/csv_stats
Internal Server Error: /dashboard/csv_stats

AttributeError at /dashboard/csv_stats
'NoneType' object has no attribute 'isSuperuser'

Request Method: HEAD
Request URL: http://ezid.cdlib.org/dashboard/csv_stats
Django Version: 4.2.15
Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
Python Version: 3.8.5

```

**Comment by sfisher** [comment]
I've corrected the internal server errors which do not happen all the time but are caused by a user not being logged in.  The fix is to use the decorator to require a logged in user for this action.  I believe this was caused by opening a few windows or tabs.  Opening the reports page and then logging out in another window and then trying to retrieve a report while logged out.

**Comment by adambuttrick** [comment]
Added with v3.2.24.
