### ISSUE TITLE
Extract failed DataCite and Crossref submissions

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#778]
Extract the failure entries from the DataCite and Crossref queues so we can review and take actions accordinly.
* DataCite queue: 1.5K+ 
* Crossref queue: 3K+

**Comment by jsjiang** [comment]
select ref.id, ref.identifier as datacite_doi, from_unixtime(q.enqueueTime), from_unixtime(q.submitTime) 
from ezidapp_datacitequeue q
join ezidapp_refidentifier ref on ref.id = q.refIdentifier_id
where q.status = 'F' order by  q.enqueueTime;


select ref.id, ref.identifier as crossref_doi, from_unixtime(q.enqueueTime), from_unixtime(q.submitTime) 
from ezidapp_crossrefqueue q
join ezidapp_refIdentifier ref on ref.id = q.refIdentifier_id
where q.status = 'F' order by  q.enqueueTime;

output files:
[failed_crossref_dois_tsv.txt](https://github.com/user-attachments/files/17603369/failed_crossref_dois_tsv.txt)
[failed_datacite_dois_tsv.txt](https://github.com/user-attachments/files/17603370/failed_datacite_dois_tsv.txt)

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam, 
I have attached DataCite and Crossref failed submissions to the ticket. Please take a look and let me know if you need more information.

Also I found a related ticket #431 (Create a weekly job to report failed Datacite and Crossref registrations). We can work on a plan on how to report and fix failed submissions.

**Comment by adambuttrick** [comment]
The majority of unique failed registrations appear to be from either the Crossref test shoulder - doi:10.15697/ or that were later migrated from being DataCite DOIs to Crossref DOIs. For the latter case, resolution testing reveals them to now be successfully registered in Crossref. These can be disregarded.

The next largest set is from International Journal of Comparative Psychology (duplicate shoulder) - doi: 10.5070/p4. Uncertain of this shoulder's history or provenance, but since it is listed as a duplicate and I can find no other public reference to the DOIs here (randomly searched for several), this can most likely be ignored.

There are a set of DOIs from the eScholarship platform that look to have either been errantly registered as DataCite DOIs or unsuccessfuly migrated from DataCite to Crossref (shoulders currently list their type Crossref), which do have public facing references, including in external sources like PubMed. These should be re-registered correctly as Crossref DOIs. Will reach out to the eScholarship team about these once I'e complete the review of the failed Crossref registrations. 

No other obvious patterns of failed registrations appear in the data, e.g. from DataCite outages. Full report is attached.

[20241108_failed_DataCite_dois.xlsx](https://github.com/user-attachments/files/17684485/20241108_failed_DataCite_dois.xlsx)

**Comment by adambuttrick** [comment]
Analyzed the Crossref entries. While being tagged as Crossref failures, most appear to failed DataCite DOI registrations that we're perhaps originally created as Crossref DOIs and migrated, were registered with the wrong type in error, or somehow otherwise populated in the wrong queue. Checking these using the DataCite verification shows that many are now correctly registered with DataCite. For those that are not, the provenance is either unclear with regard to the intent (meaning, I can't discern if this was supposed to be a Crossref DOI at some point) or the shoulders all appear to be associated with the type DataCite. Many also has no metadata or had such minimal metadata (e.g. a single field populated) that they would not register successfully in either schema. None of the DOIs that lacked a corresponding/working DataCite DOI registration appear to have public facing references (spot-checked many for each shoulder), with the exception of doi:10.5063/f14748bd, which I corrected by simply resaving the record. 

No other obvious patterns of failed registrations appear in the data from outages. Full report is attached.
[20241110_failed_Crossref_dois.xlsx](https://github.com/user-attachments/files/17692554/20241110_failed_Crossref_dois.xlsx)

**Comment by adambuttrick** [comment]
#### Actions
- [ ] Report failed eScholarship registrations to the eScholarship team for correction
- [ ] Failures extracted here can be purged.
